name: Triggered Workflow with Parameter

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_PAT_TOKEN }}
      
      - name: Use folder name parameter
        run: |
          echo "Folder Name: ${{ github.event.inputs.folder_name }}"
          pwd
          ls -a
          mkdir image_folder
          cd image_folder
          touch sample.txt
          echo "==========================================================" >> sample.txt
          echo "Folder Name: ${{ github.event.inputs.folder_name }}" >> sample.txt
          echo "hello lokesh this is in cat" >> sample.txt
          echo "==========================================================" >> sample.txt
          cat sample.txt
          git config user.email "winadm1n@protonmail.com"
          git config user.name "winadm1n"
          git add .
          git commit -m "Move files to new folder"
          git push origin main 
